CREATE TABLE `ab_test_experiments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`targetType` enum('deployment','container','service') NOT NULL DEFAULT 'deployment',
	`targetName` varchar(255) NOT NULL,
	`namespace` varchar(255),
	`status` enum('draft','running','paused','completed','cancelled') NOT NULL DEFAULT 'draft',
	`variantAName` varchar(100) NOT NULL DEFAULT 'Control',
	`variantAScaleUpThreshold` int NOT NULL,
	`variantAScaleDownThreshold` int NOT NULL,
	`variantACooldown` int NOT NULL DEFAULT 300,
	`variantAMinReplicas` int NOT NULL DEFAULT 1,
	`variantAMaxReplicas` int NOT NULL DEFAULT 10,
	`variantBName` varchar(100) NOT NULL DEFAULT 'Treatment',
	`variantBScaleUpThreshold` int NOT NULL,
	`variantBScaleDownThreshold` int NOT NULL,
	`variantBCooldown` int NOT NULL DEFAULT 300,
	`variantBMinReplicas` int NOT NULL DEFAULT 1,
	`variantBMaxReplicas` int NOT NULL DEFAULT 10,
	`trafficSplitPercent` int NOT NULL DEFAULT 50,
	`startedAt` timestamp,
	`endedAt` timestamp,
	`durationHours` int NOT NULL DEFAULT 24,
	`winnerVariant` enum('A','B','inconclusive'),
	`winnerConfidence` int,
	`winnerReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ab_test_experiments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ab_test_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`experimentId` int NOT NULL,
	`variant` enum('A','B') NOT NULL,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`avgCpuPercent` int NOT NULL,
	`avgMemoryPercent` int NOT NULL,
	`avgResponseTimeMs` int,
	`errorRate` int,
	`scaleUpCount` int NOT NULL DEFAULT 0,
	`scaleDownCount` int NOT NULL DEFAULT 0,
	`avgReplicaCount` int NOT NULL,
	`estimatedCostUnits` int,
	`oscillationCount` int NOT NULL DEFAULT 0,
	`cooldownViolations` int NOT NULL DEFAULT 0,
	CONSTRAINT `ab_test_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_scaling_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` int NOT NULL,
	`applicationId` int,
	`predictedMetricValue` int NOT NULL,
	`predictedTime` timestamp NOT NULL,
	`recommendedReplicas` int NOT NULL,
	`confidence` int NOT NULL,
	`reasoning` text NOT NULL,
	`dataPointsAnalyzed` int NOT NULL,
	`patternDetected` varchar(100),
	`isActedUpon` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_scaling_predictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `autoscaling_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` int NOT NULL,
	`applicationId` int,
	`action` enum('scale_up','scale_down','no_action','pending_approval','rejected','failed') NOT NULL,
	`previousReplicas` int NOT NULL,
	`newReplicas` int NOT NULL,
	`triggerMetric` varchar(50) NOT NULL,
	`triggerValue` int NOT NULL,
	`thresholdValue` int NOT NULL,
	`aiAnalysis` text,
	`aiConfidence` int,
	`aiRecommendation` text,
	`executedBy` enum('ai','manual','scheduled') NOT NULL DEFAULT 'ai',
	`approvedBy` int,
	`status` enum('pending','executing','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`executionTimeMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `autoscaling_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `autoscaling_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`resourceType` enum('deployment','container','pod','service') NOT NULL,
	`resourcePattern` varchar(255) NOT NULL,
	`namespace` varchar(255),
	`metricType` enum('cpu','memory','requests','custom') NOT NULL,
	`scaleUpThreshold` int NOT NULL,
	`scaleDownThreshold` int NOT NULL,
	`minReplicas` int NOT NULL DEFAULT 1,
	`maxReplicas` int NOT NULL DEFAULT 10,
	`cooldownSeconds` int NOT NULL DEFAULT 300,
	`scaleUpStep` int NOT NULL DEFAULT 1,
	`scaleDownStep` int NOT NULL DEFAULT 1,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`requiresApproval` boolean NOT NULL DEFAULT false,
	`aiAssisted` boolean NOT NULL DEFAULT true,
	`lastScaledAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autoscaling_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduled_scaling` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`targetType` enum('deployment','container','service') NOT NULL DEFAULT 'deployment',
	`targetName` varchar(255) NOT NULL,
	`namespace` varchar(255),
	`cronExpression` varchar(100) NOT NULL,
	`timezone` varchar(50) NOT NULL DEFAULT 'UTC',
	`targetReplicas` int NOT NULL,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`lastExecutedAt` timestamp,
	`nextExecutionAt` timestamp,
	`executionCount` int NOT NULL DEFAULT 0,
	`failureCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduled_scaling_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduled_scaling_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduleId` int NOT NULL,
	`previousReplicas` int NOT NULL,
	`targetReplicas` int NOT NULL,
	`actualReplicas` int,
	`status` enum('pending','executing','completed','failed','skipped') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`executionTimeMs` int,
	`scheduledFor` timestamp NOT NULL,
	`executedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scheduled_scaling_history_id` PRIMARY KEY(`id`)
);
