CREATE TABLE `canary_deployment_steps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deploymentId` int NOT NULL,
	`stepNumber` int NOT NULL,
	`targetPercent` int NOT NULL,
	`status` enum('pending','running','completed','failed','skipped') NOT NULL DEFAULT 'pending',
	`requestCount` int DEFAULT 0,
	`errorCount` int DEFAULT 0,
	`avgLatencyMs` int,
	`p99LatencyMs` int,
	`successRate` int,
	`healthyPods` int,
	`totalPods` int,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `canary_deployment_steps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `canary_deployments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`applicationId` int,
	`clusterId` int,
	`name` varchar(255) NOT NULL,
	`namespace` varchar(255) DEFAULT 'default',
	`targetDeployment` varchar(255) NOT NULL,
	`stableVersion` varchar(100),
	`canaryVersion` varchar(100),
	`stableImage` varchar(500),
	`canaryImage` varchar(500),
	`trafficSplitType` enum('percentage','header','cookie') NOT NULL DEFAULT 'percentage',
	`initialCanaryPercent` int NOT NULL DEFAULT 10,
	`currentCanaryPercent` int NOT NULL DEFAULT 0,
	`targetCanaryPercent` int NOT NULL DEFAULT 100,
	`incrementPercent` int NOT NULL DEFAULT 10,
	`incrementIntervalMinutes` int NOT NULL DEFAULT 5,
	`errorRateThreshold` int NOT NULL DEFAULT 5,
	`latencyThresholdMs` int NOT NULL DEFAULT 1000,
	`successRateThreshold` int NOT NULL DEFAULT 95,
	`minHealthyPods` int NOT NULL DEFAULT 1,
	`autoRollbackEnabled` boolean NOT NULL DEFAULT true,
	`rollbackOnErrorRate` boolean NOT NULL DEFAULT true,
	`rollbackOnLatency` boolean NOT NULL DEFAULT true,
	`rollbackOnPodFailure` boolean NOT NULL DEFAULT true,
	`maxRollbackAttempts` int NOT NULL DEFAULT 3,
	`analysisIntervalSeconds` int NOT NULL DEFAULT 30,
	`minAnalysisDuration` int NOT NULL DEFAULT 60,
	`requireManualApproval` boolean NOT NULL DEFAULT false,
	`status` enum('pending','initializing','progressing','paused','promoting','promoted','rolling_back','rolled_back','failed','cancelled') NOT NULL DEFAULT 'pending',
	`statusMessage` text,
	`startedAt` timestamp,
	`lastProgressAt` timestamp,
	`completedAt` timestamp,
	`createdBy` varchar(255),
	`gitCommit` varchar(100),
	`gitBranch` varchar(255),
	`pullRequestUrl` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `canary_deployments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `canary_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deploymentId` int NOT NULL,
	`stepId` int,
	`canaryPercent` int NOT NULL,
	`canaryRequests` int DEFAULT 0,
	`stableRequests` int DEFAULT 0,
	`canaryErrors` int DEFAULT 0,
	`stableErrors` int DEFAULT 0,
	`canaryErrorRate` int,
	`stableErrorRate` int,
	`canaryAvgLatency` int,
	`stableAvgLatency` int,
	`canaryP50Latency` int,
	`stableP50Latency` int,
	`canaryP95Latency` int,
	`stableP95Latency` int,
	`canaryP99Latency` int,
	`stableP99Latency` int,
	`canaryHealthyPods` int,
	`canaryTotalPods` int,
	`stableHealthyPods` int,
	`stableTotalPods` int,
	`canaryCpuPercent` int,
	`stableCpuPercent` int,
	`canaryMemoryPercent` int,
	`stableMemoryPercent` int,
	`analysisResult` enum('healthy','degraded','unhealthy','inconclusive') DEFAULT 'inconclusive',
	`analysisNotes` text,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `canary_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `canary_rollback_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deploymentId` int NOT NULL,
	`trigger` enum('auto_error_rate','auto_latency','auto_pod_failure','auto_health_check','manual','timeout','cancelled') NOT NULL,
	`triggerValue` varchar(255),
	`thresholdValue` varchar(255),
	`canaryPercentAtRollback` int NOT NULL,
	`stepAtRollback` int,
	`status` enum('pending','in_progress','completed','failed') NOT NULL DEFAULT 'pending',
	`rollbackToVersion` varchar(100),
	`rollbackToImage` varchar(500),
	`initiatedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`initiatedBy` varchar(255),
	`reason` text,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `canary_rollback_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `canary_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`trafficSplitType` enum('percentage','header','cookie') NOT NULL DEFAULT 'percentage',
	`initialCanaryPercent` int NOT NULL DEFAULT 10,
	`incrementPercent` int NOT NULL DEFAULT 10,
	`incrementIntervalMinutes` int NOT NULL DEFAULT 5,
	`errorRateThreshold` int NOT NULL DEFAULT 5,
	`latencyThresholdMs` int NOT NULL DEFAULT 1000,
	`successRateThreshold` int NOT NULL DEFAULT 95,
	`autoRollbackEnabled` boolean NOT NULL DEFAULT true,
	`requireManualApproval` boolean NOT NULL DEFAULT false,
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `canary_templates_id` PRIMARY KEY(`id`)
);
